import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import Providers from '@/lib/providers';
import Header from '@/components/layout/header';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Providers>
			<html lang="en">
				<body className={`${manrope.className} antialiased`}>
					<Header />
					{children}
				</body>
			</html>
		</Providers>
	);
}
